JobAppMgr/JobAppMgr/Controllers/AgencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Interfaces;
using Core.Model;
using JobAppMgr.Mappings;
using JobAppMgr.ViewModels;

namespace JobAppMgr.Controllers
{
    public class AgencyController : Controller
    {
        private readonly IAgencyRepository _repository;
        private readonly IContactRepository _contactRepository;

        public AgencyController(IAgencyRepository repository, IContactRepository contactRepository)
        {
            if (repository == null)
                throw new ArgumentNullException("repository", "No valid repository supplied to AgencyController.");
            if (contactRepository == null)
                throw new ArgumentNullException("contactRepository", "No valid ContactRepository supplied to Agency Controller");
            _repository = repository;
            _contactRepository = contactRepository;
        }


        //
        // GET: /Agency/

        public ActionResult Index()
        {
            var agencies = _repository.GetAll();
            var count = agencies.Count();
            ViewBag.Message = string.Format(" {0} Compan{1} found", count,
                (count > 1) ? "ies" : "y");
            var viewModel = (new MapAgencyToAgencyListViewModel()).Map(agencies);
            return View(viewModel);
        }

        //
        // GET: /Agency/Details/5

        public ActionResult Details(int id)
        {
            var agency = _repository.Get(id);
            ViewBag.Message = agency.Name;
            var viewModel = (new MapAgencyToAgencyViewModel()).Map(agency);
            return View(viewModel);
        }

        //
        // GET: /Agency/Create

        public ActionResult Create()
        {
            var viewModel = new AgencyViewModel()
            {
                Id = 0,
                Name = String.Empty,
                Address = string.Empty
            };
            return View(viewModel);
        }

        //
        // POST: /Agency/Create

        [HttpPost]
        public ActionResult Create(AgencyViewModel agencyViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var agency = (new MapAgencyViewModelToAgency()).Map(agencyViewModel);
                    var result = _repository.Create(agency);
                    TempData.Add("Msg", string.Format("Agency '({0}) {1}' successfully created", result.Id, result.Name));
                    return RedirectToAction("Index");
                }
                return View(agencyViewModel);      //  Model not valid
            }
            catch
            {
                return View(agencyViewModel);
            }
        }

        //
        // GET: /Agency/Edit/5

        public ActionResult Edit(int id)
        {
            var agency = _repository.Get(id);
            ViewBag.Message = agency.Name;
            var viewModel = (new MapAgencyToAgencyViewModel()).Map(agency);
            return View(viewModel);
        }

        //
        // POST: /Agency/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, AgencyViewModel agencyViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var agency = (new MapAgencyViewModelToAgency()).Map(agencyViewModel);
                    var result = _repository.Update(agency);
                    TempData.Add("Msg", string.Format("Agency '{0} successfully updated", agency.Name));
                    return RedirectToAction("Index");
                }
                return View(agencyViewModel);      //  Model not valid
            }
            catch
            {
                return View(agencyViewModel);
            }
        }

        ////
        //// GET: /Agency/Delete/5

        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        ////
        //// POST: /Agency/Delete/5

        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        public ActionResult AddContact(int id)
        {
            var agency = _repository.Get(id);
            var contacts = _contactRepository.GetAvailableContacts(agency.Contacts);   //.ToEnum("Name");

            ViewBag.Message = agency.Name;

            var viewModel = new AddOrganisationContactsViewModel<AgencyViewModel>()
            {
                Organisation = (new MapAgencyToAgencyViewModel()).Map(agency),
                ContactId = 0,
                AvailableContacts = new SelectList(contacts, "Id", "Name")
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddContact(int id, AddOrganisationContactsViewModel<AgencyViewModel> viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //  TODO: refactor contact adding logic to remove from Controller method.
                    var addedContact = _contactRepository.Get(viewModel.ContactId);
                    var agency = _repository.Get(id);
                    agency.Contacts.Add(addedContact);
                    var result = _repository.Update(agency);
                    TempData.Add("Msg", string.Format("Contact '{0}' successfully added to Agency '{1}'", addedContact.Name, agency.Name));
                    return RedirectToAction("Index");
                }

                //  TODO: factor in retrieving the company information again as display only is lost by now.
                var reloadedAgency = _repository.Get(id);
                viewModel.Organisation = (new MapAgencyToAgencyViewModel()).Map(reloadedAgency);
                var contacts = _contactRepository.GetAvailableContacts(reloadedAgency.Contacts);   //.ToEnum("Name");
                viewModel.AvailableContacts = new SelectList(contacts, "Id", "Name");
                return View(viewModel);
            }
            catch (Exception)
            {
                return View();
            }
        }

    }
}

JobAppMgr/JobAppMgr/Controllers/JobController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Interfaces;
using Core.Model;
using JobAppMgr.Mappings;
using JobAppMgr.ViewModels;

namespace JobAppMgr.Controllers
{
    public class JobController : Controller
    {
        private readonly IJobApplicationRepository _repository;
        private readonly ICompanyRepository _companyRepository;
        private readonly IAgencyRepository _agencyRepository;
        private readonly IStatusRepository _statusRepository;
        private readonly IEventTypeRepository _eventTypeRepository;

        private const string DocsPath = "~/Documents";

        public JobController(IJobApplicationRepository repository, 
            ICompanyRepository companyRepository, 
            IAgencyRepository agencyRepository,
            IStatusRepository statusRepository,
            IEventTypeRepository eventTypeRepository)
        {
            if (repository == null)
                throw new ArgumentNullException("repository", "No valid JobApplicationRepository supplied to Job Controller");
            if (companyRepository == null)
                throw new ArgumentNullException("companyRepository", "No valid CompanyRepository supplied to JobController");
            if (agencyRepository == null)
                throw new ArgumentNullException("agencyRepository", "No valid AgencyRepository supplied to JobController");
            if (statusRepository == null)
                throw new ArgumentNullException("statusRepository", "No valid StatusRepository supplied to JobController");
            if (eventTypeRepository == null)
                throw new ArgumentNullException("eventTypeRepository", "No valid EventTypeRepository supplied to JoobController");
            _repository = repository;
            _companyRepository = companyRepository;
            _agencyRepository = agencyRepository;
            _statusRepository = statusRepository;
            _eventTypeRepository = eventTypeRepository;
        }

        //
        // GET: /Job/

        public ActionResult Index()
        {
            var jobs = _repository.GetAll();
            var count = jobs.Count();
            ViewBag.Message = string.Format(" {0} Application{1} found", count, (count > 1) ? "s" : "");
            var viewModel = (new Mappings.MapJobApplicationsToJobListViewModel()).Map(jobs);
            return View(viewModel);
        }

        //
        // GET: /Job/Details/5

        public ActionResult Details(int id)
        {
            var job = _repository.Get(id);

            var mapper = new MapJobApplicationToJobDetailsViewModel();
            var viewModel = mapper.Map(job);

            ViewBag.Message = string.Format("{0}, {1}", job.Title, job.Company.Name);
            return View(viewModel);
        }

        //
        // GET: /Job/Create

        public ActionResult Create()
        {
            var agencies = _agencyRepository.GetAll();
            var companies = _companyRepository.GetAll();

            var viewModel = new JobEditViewModel()
            {
                CreateDate = DateTime.Now,
                Companies = new SelectList(companies, "Id", "Name"),
                Agencies = new SelectList(agencies, "Id", "Name"),
            };

            return View(viewModel);
        }

        //
        // POST: /Job/Create

        [HttpPost]
        public ActionResult Create(JobEditViewModel jobEditViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var mapper = new MapJobViewModelToJobApplication();
                    var job = mapper.Map(jobEditViewModel);

                    //  Retrieve the company in case it's been updated.
                    var company = _companyRepository.Get(jobEditViewModel.CompanyId);
                    job.Company = company;

                    var agency = _agencyRepository.Get(jobEditViewModel.AgencyId);
                    job.Agency = agency;

                    job.Status = _statusRepository.Get(1);

                    var result = _repository.Create(job);

                    TempData.Add("Msg", string.Format("Job Application '{0}' successfully created", job.Title));
                    return RedirectToAction("Index");
                }
                return View(jobEditViewModel);      //  Model not valid
            }
            catch
            {
                return View(jobEditViewModel);
            }
        }

        //
        // GET: /Job/Edit/5

        public ActionResult Edit(int id)
        {
            var job = _repository.Get(id);
            var companies = _companyRepository.GetAll();
            var agencies = _agencyRepository.GetAll();

            var mapper = new MapJobApplicationToJobEditViewModel();
            var viewModel = mapper.Map(job);
            
            viewModel.Companies = new SelectList(companies, "Id", "Name");
            viewModel.Agencies = new SelectList(agencies, "Id", "Name");

            ViewBag.Message = string.Format("{0}, {1}", job.Title, job.Company.Name);
            return View(viewModel);
        }

        //
        // POST: /Job/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, JobEditViewModel jobEditViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var mapper = new MapJobViewModelToJobApplication();
                    var job = mapper.Map(jobEditViewModel);

                    //  Retrieve the company in case it's been updated.
                    var company = _companyRepository.Get(jobEditViewModel.CompanyId);
                    job.Company = company;

                    var agency = _agencyRepository.Get(jobEditViewModel.AgencyId);
                    job.Agency = agency;

                    var result = _repository.Update(job);

                    TempData.Add("Msg", string.Format("Job Application '{0}' successfully updated", job.Title));
                    return RedirectToAction("Index");
                }
                return View(jobEditViewModel);      //  Model not valid
            }
            catch
            {
                return View(jobEditViewModel);
            }
        }

        ////
        //// GET: /Job/Delete/5

        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        ////
        //// POST: /Job/Delete/5

        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        public ActionResult AddEvent(int id)
        {
            var job = _repository.Get(id);

            var viewModel = new AddJobApplicationEventViewModel();
            viewModel.JobApplication = (new MapJobApplicationsToJobListViewModel()).Map(job);
            viewModel.Events = (new MapEventToEventListviewModel()).Map(_repository.GetJobEvents(id));
            viewModel.PossibleEventTypes = PopulateEventTypes(job.Events);

            viewModel.NewEvent = new AddEventViewModel()
            {
                Id = 0,
                Date = DateTime.Now.ToString(),
                Details = string.Empty,
                Attachment = string.Empty
            };

            ViewBag.Message = string.Format("{0}, {1}", job.Title, job.Company.Name);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddEvent(int id, AddJobApplicationEventViewModel viewModel,  HttpPostedFileBase myfile)
        {
            try
            {
                JobApplication job;
                if (ModelState.IsValid)
                {
                    job = _repository.Get(id);

                    var savedFiles = SaveAnyFiles(Request.Files, job.Id);

                    var addedEvent = (new MapAddEventViewModelToEvent()).Map(viewModel.NewEvent);
                    addedEvent.JobApplicationId = id;
                    addedEvent.Attachment = savedFiles.FirstOrDefault();

                    job.Events.Add(addedEvent);

                    _repository.Update(job);

                    TempData.Add("Msg", string.Format("Event successfully added to job application "));
                    return RedirectToAction("AddEvent");

                }
                //  Model invalid, return the view
                job = _repository.Get(id);
                //  Repopulate the static content.
                viewModel.JobApplication = (new MapJobApplicationsToJobListViewModel()).Map(job);
                viewModel.Events = (new MapEventToEventListviewModel()).Map(job.Events);
                viewModel.PossibleEventTypes = PopulateEventTypes(job.Events);

                return View(viewModel);
            }
            catch (Exception)
            {
                return View();
            }
        }


        private SelectList PopulateEventTypes(IEnumerable<Event> jobEvents)
        {
            IQueryable<EventType> possibleEventTypes = null;

            if (jobEvents == null)
                possibleEventTypes = _eventTypeRepository.GetInitialTypes();
            else
            {
                var events = jobEvents.ToList();        //  Avoid multiple iterations of IEnumerable<>
                if (events.Count == 0)
                    possibleEventTypes = _eventTypeRepository.GetInitialTypes();
                else
                {
                    var lastEvent = events.LastOrDefault();
                    var lastEventType = _eventTypeRepository.Get(lastEvent.EventTypeId);

JobAppMgr/JobAppMgr/Views/Shared/ContactListPartial.cshtml
@model IEnumerable<JobAppMgr.ViewModels.ContactViewModel>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @* Use overload that allows the controller to be specified.
                NB!  MUST include the HtmlArguments parameter at the 
                end to ensure the correct overload is used and therefore
                the reference is resolved correctly. 
                This ensures that the link points to the /Contact/Edit/id,
                even from the Company or Agency Details page.
                *@
            @Html.ActionLink(item.Name, "Edit", "Contact", new { id = item.Id }, null)
            @*@Html.DisplayFor(modelItem => item.Name)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
    </tr>
}

</table>

JobAppMgr/JobAppMgr/Views/Shared/ContactListPartialDiv.cshtml
@model IEnumerable<JobAppMgr.ViewModels.ContactViewModel>

<div class="table">
    <div class="tableHeader">
        <div class="tableColumnHeader">
            @Html.DisplayNameFor(model => model.Name)
        </div>
        <div class="tableColumnHeader">
            @Html.DisplayNameFor(model => model.Phone)
        </div>
    </div>

@foreach (var item in Model) {
    <div class="tableRow">
        <div class="tableColumn">
            @* Use overload that allows the controller to be specified.
                NB!  MUST include the HtmlArguments parameter at the 
                end to ensure the correct overload is used and therefore
                the reference is resolved correctly. 
                This ensures that the link points to the /Contact/Edit/id,
                even from the Company or Agency Details page.
                *@
            @Html.ActionLink(item.Name, "Edit", "Contact", new { id = item.Id }, null)
            @*@Html.DisplayFor(modelItem => item.Name)*@
        </div>
        <div class="tableColumn">
            @Html.DisplayFor(modelItem => item.Phone)
        </div>
    </div>
}

</div>

JobAppMgr/JobAppMgr/Views/Shared/JobListPartial.cshtml
@model IEnumerable<JobAppMgr.ViewModels.JobListViewModel>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClosingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AgencyName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.HiddenFor(modelItem => item.Id)
            @Html.ActionLink(item.Title, "Details", "Job", new { id = item.Id }, new { Title = "View details of Job Application"})
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClosingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AgencyName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Job", new { id=item.Id }, new { Title = "Edit the Job Application"}) |
            @Html.ActionLink("Add Event", "AddEvent", "Job", new { id=item.Id }, new { Title = "Add an event to the Job Application"})
        </td>
    </tr>
}

</table>

JobAppMgr/JobAppMgr/Views/Shared/JobListPartialDiv.cshtml
@model IEnumerable<JobAppMgr.ViewModels.JobListViewModel>

<div class="table">
    <div class="tableHeader">
        <div class ="tableColumnHeader" >
            @Html.DisplayNameFor(model => model.Title)
        </div>
        <div class="tableColumnHeader">
            @Html.DisplayNameFor(model => model.StatusName)
        </div>
        <div class="tableColumnHeader">
            @Html.DisplayNameFor(model => model.ClosingDate)
        </div>
        <div class="tableColumnHeader">
            @Html.DisplayNameFor(model => model.Location)
        </div>
        <div class="tableColumnHeader">
            @Html.DisplayNameFor(model => model.CompanyName)
        </div>
        <div class="tableColumnHeader">
            @Html.DisplayNameFor(model => model.AgencyName)
        </div>
        <div class="tableColumnHeader"></div>
    </div>

@foreach (var item in Model) {
    <div class="tableRow">
        <div class="tableColumn">
            @Html.HiddenFor(modelItem => item.Id)
            @Html.ActionLink(item.Title, "Details", "Job", new { id = item.Id }, new { Title = "View details of Job Application"})
        </div>
        <div class="tableColumn">
            @Html.DisplayFor(modelItem => item.StatusName)
        </div>
        <div class="tableColumn">
            @Html.DisplayFor(modelItem => item.ClosingDate)
        </div>
        <div class="tableColumn">
            @Html.DisplayFor(modelItem => item.Location)
        </div>
        <div class="tableColumn">
            @Html.DisplayFor(modelItem => item.CompanyName)
        </div>
        <div class="tableColumn">
            @Html.DisplayFor(modelItem => item.AgencyName)
        </div>
        <div class="tableColumn">
            @Html.ActionLink("Edit", "Edit", "Job", new { id = item.Id }, new { Title = "Edit the Job Application" }) |
            @Html.ActionLink("Add Event", "AddEvent", "Job", new { id = item.Id }, new { Title = "Add an event to the Job Application" })
        </div>
    </div>
}

</div>

JobAppMgr/JobAppMgr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title1</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div>
            <header>
                <div class="content-wrapper">
                    <div class="float-left">
                        <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                    </div>
                    <div class="float-right">
                        <section id="login">
                            @Html.Partial("_LoginPartial")
                        </section>
                        @Html.Partial("_MenuPartial")
                    </div>
                </div>
            </header>
            <div id="body">
                @RenderSection("featured", required: false)
                <section class="content-wrapper main-content clear-fix">
                    @RenderBody()
                </section>
            </div>
            <footer>
                <div class="content-wrapper">
                    <div class="float-left">
                        <p>&copy; @DateTime.Now.Year - Job Applications Manager</p>
                    </div>
                </div>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

JobAppMgr/JobAppMgr/Views/Shared/_MenuPartial.cshtml
@using System.Activities.Expressions
<nav id="cssmenu">
    <ul>
        <li id="Home">@Html.ActionLink("Home", "Index", "Home", null, new { Title = "Return to the Home page" })</li>
        <li class="has-sub">
            @Html.ActionLink("Applications", "Index", "Job", null, new { Title = "List all Job Applications"})
        </li>
        <li class="has-sub">
            <a id="h" href="">
                <span title="Organisations">Organisations</span>
            </a>
            <ul>
                <li class="has-sub">
                    <a id="h" href="">
                        <span title="Companies">Companies</span>
                    </a>
                    <ul>
                        <li>@Html.ActionLink("List", "Index", "Company", null, new { Title = "Show List a Companies" })</li>
                        <li>@Html.ActionLink("Create", "Create", "Company", null, new { Title = "Create a new company" })</li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a id="h" href="">
                        <span title="Agencies">Agencies</span>
                    </a>
                    <ul>
                        <li>@Html.ActionLink("List", "Index", "Agency", null, new { Title = "Show a list of Agencies" })</li>
                        <li>@Html.ActionLink("Create", "Create", "Agency", null, new { Title = "Create a new Agency" })</li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a id="h" href="">
                        <span title="Work with Contacts">Contacts</span>
                    </a>
                    <ul>
                        <li>@Html.ActionLink("List", "Index", "Contact", null, new { Title = "Show a list of contacts that belong to the Organisations" })</li>
                        <li>@Html.ActionLink("Create", "Create", "Contact", null, new { Title = "Create a new Contact" })</li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>@Html.ActionLink("About", "About", "Home", null, new { Title = "Website Details" })</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home", null, new { Title = "Contact the Authors of the Website" })</li>
    </ul>
</nav>